//! SeaORM Entity. Generated by sea-orm-codegen 0.9.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "bid")]
pub struct Model {
    pub timestamp: DateTime,
    pub username: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub price: Decimal,
    #[sea_orm(primary_key, auto_increment = false)]
    pub auction_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::auction::Entity",
        from = "Column::AuctionId",
        to = "super::auction::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Auction,
}

impl Related<super::auction::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Auction.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
